--Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

--1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

--By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

main = print $ sum $ filter (\x -> x `mod` 2 == 0) fibs4mil

fibs4mil = takeWhile (<= 4000000) fibs

fibs = 0 : 1 : zipWith (+) fibs (tail fibs)

{-fibs = map fibsN [1..]

fibsN 1 = 1
fibsN 2 = 1
fibsN n = (fibsN (n-2)) + (fibsN (n-1))-}